export const copyENA = {
    appName: "QueueMint",
    appTagline: "Create one issue fast, or import a whole batch and review it before Jira.",
    connected: "Connected",
    disconnected: "Not connected",
    reconnect: "Reconnect",
    openJira: "Open Jira",
    connectJira: "Connect Jira",
    onboardingTitle: "Connect your Jira workspace",
    onboardingHint: "Use the Jira tab you came from, or enter another Jira URL. No demo project is loaded automatically.",
    currentJiraTab: "Use current Jira tab",
    jiraUrl: "Jira URL",
    jiraUrlPlaceholder: "https://jira.company.com",
    connect: "Connect",
    skipForNow: "Skip for now",
    chooseJiraTab: "Jira tabs",
    chooseJiraTabHint: "Multiple Jira tabs are open. Requests use the selected tab; you can switch safely here.",
    useThisTab: "Use this tab",
    tabInUse: "In use",
    noJiraTabs: "No Jira tabs are open for this site.",
    connectedSite: "Connected site",
    differentJiraSite: "Another Jira site was detected",
    differentJiraSiteDescription: "The extension was opened from a different Jira site. Connect it if you want to switch workspaces.",
    multipleTabsToast: "Multiple Jira tabs detected",
    multipleTabsDescription: "Using the most recently selected Jira tab. You can switch from the connection panel.",
    contextDetected: "Jira context detected",
    contextDetectedDescription: "Project and active board context were picked from your Jira tab.",
    activeSprintDetected: "Active sprint selected",
    connectionReady: "Jira connected",
    connectionFailed: "Could not connect to Jira",
    validationPassed: "Validation passed",
    validationFailed: "Fix validation errors before creating issues",
    createSucceeded: "Issues created successfully",
    quickCreateSucceeded: "Issue created successfully",
    updateSucceeded: "Jira issues updated",
    deleteSucceeded: "Selected Jira issues deleted",
    importSucceeded: "Batch imported",
    importFailed: "Could not read this Jira batch",
    quick: "Quick issue",
    bulk: "Bulk import",
    review: "Review & create",
    manage: "Manage Jira",
    quickTitle: "Create one Jira issue",
    quickHint: "A short path for the issue you need right now.",
    bulkTitle: "Import a Jira batch",
    bulkHint: "Paste JSON, upload a file, or download a safe example for AI.",
    reviewTitle: "Review before Jira",
    reviewHint: "Check placement and details without keeping JSON in your face.",
    manageTitle: "Manage created work",
    manageHint: "Fix placement, priority, ownership, estimates, or delete issues in bulk after creation.",
    contextMismatchTitle: "Jira context and workspace do not match",
    contextMismatchDescription: "The Jira tab you are using points to another project. Choose which context should drive this workspace.",
    useCurrentJiraContext: "Use current Jira context",
    keepWorkspace: "Keep current workspace",
    chooseTab: "Choose Jira tab",
    skippedOnboardingTitle: "Jira is not connected yet",
    skippedOnboardingDescription: "Connect the Jira tab you are already using. Your current draft stays untouched.",
    largeBoardHint: "Large board detected. List view is optimized for faster scanning and bulk work.",
    listView: "List",
    boardViewLive: "Board",
    filtersLabel: "Filters",
    myIssues: "My issues",
    allAssignees: "All assignees",
    allPriorities: "All priorities",
    allStatuses: "All statuses",
    allSprints: "All sprints",
    allLabels: "All labels",
    allEstimates: "All estimates",
    estimated: "Estimated",
    unestimated: "No estimate",
    activeFilters: "active filters",
    clearFilters: "Clear filters",
    selectVisible: "Select visible",
    selectMatching: "Select all matching",
    selectedMatching: "All matching issues selected",
    page: "Page",
    of: "of",
    rowsPerPage: "Rows",
    estimate: "Estimate",
    storyPoints: "Story points",
    originalEstimate: "Original estimate",
    remainingEstimate: "Remaining estimate",
    estimatePlaceholder: "e.g. 3h, 2d, 30m",
    estimateHelp: "Jira duration format: 30m, 3h, 2d, or combinations like 1d 4h.",
    defaultEstimate: "Default estimate",
    inheritedEstimate: "Uses batch default when empty",
    estimateUnavailable: "Time tracking is not available for this Jira connection.",
    estimateApplyFailed: "Some estimates could not be applied",
    editEstimate: "Change estimate",
    status: "Status",
    open: "Open",
    bulkActions: "Bulk actions",
    createdBatch: "Created batch",
    wholeBoard: "Whole board",
    refreshBoard: "Refresh board",
    bulkEdit: "Bulk edit",
    bulkEditPreview: "Review changes",
    bulkEditPreviewHint: "QueueMint will show the current value and the new value before anything is written to Jira.",
    beforeValue: "Before",
    afterValue: "After",
    confirmBulkEdit: "Apply to Jira",
    backToEdit: "Back to edit",
    preparingPreview: "Preparing change preview…",
    dynamicFields: "Additional Jira fields",
    dynamicFieldsHint: "Fields are loaded from Jira edit metadata for the selected issue types.",
    addJiraField: "Add Jira field",
    noDynamicFields: "No additional editable Jira fields were exposed for this selection.",
    fieldAvailability: "Available on {count}/{total} selected issue types",
    setValue: "Set value",
    clearValue: "Clear value",
    removeField: "Remove field",
    fieldRequired: "Required",
    mixedValues: "Mixed values",
    history: "History",
    changeHistory: "Bulk change history",
    historyHint: "Recent QueueMint bulk edits are kept in this session so you can restore the previous values.",
    noHistory: "No bulk edits yet.",
    undo: "Undo",
    undoing: "Undoing…",
    undoComplete: "Previous Jira values were restored.",
    undoPartial: "Some Jira values could not be restored.",
    changes: "changes",
    issuesAffected: "issues affected",
    assignToMe: "Assign to me",
    applyChanges: "Apply changes",
    noChange: "No change",
    selectedIssues: "Selected issues",
    deleteSelected: "Delete selected",
    confirmDeleteTitle: "Delete selected Jira issues?",
    confirmDeleteDescription: "This is irreversible. Type DELETE to confirm deletion of the selected Jira issues.",
    typeDelete: "Type DELETE",
    deleteNow: "Delete permanently",
    boardEmpty: "No Jira issues were found for this board view.",
    boardLoading: "Loading Jira board…",
    dragHint: "Drag cards between Sprint and Backlog, or use the bulk actions for keyboard-friendly movement.",
    draftCleared: "Created successfully. The draft batch was cleared.",
    createdReviewPlacement: "Issues were created. Review Sprint/Backlog placement below because Jira could not place every issue as planned.",
    createdReviewEstimate: "Issues were created, but some estimates need review. Use bulk edit below to retry them.",
    postCreateHelp: "The issues below already exist in Jira. Changes here update Jira directly.",
    editPriority: "Change priority",
    editAssignee: "Change assignee",
    editPlacement: "Change placement",
    editIssueType: "Change issue type",
    editEpicLink: "Change Epic Link",
    removeEpicLink: "Remove Epic Link",
    unassign: "Unassign",
    permissionsDenied: "Your Jira permissions do not allow this action.",
    updateComplete: "Bulk update completed.",
    updatePartial: "Some Jira issues could not be updated.",
    deleteComplete: "Selected Jira issues were deleted.",
    project: "Project",
    board: "Board",
} as const
