export const copyFAA = {
    appName: "QueueMint",
    appTagline: "یک تسک را سریع بساز یا یک دسته کامل را وارد کن، بررسی کن و بعد به Jira بفرست.",
    connected: "متصل",
    disconnected: "قطع اتصال",
    reconnect: "اتصال مجدد",
    openJira: "باز کردن Jira",
    connectJira: "اتصال Jira",
    onboardingTitle: "Jira خودتان را متصل کنید",
    onboardingHint: "از تب Jira که از آن آمده‌اید استفاده کنید یا آدرس Jira دیگری وارد کنید. هیچ پروژه نمونه‌ای خودکار بارگذاری نمی‌شود.",
    currentJiraTab: "استفاده از تب فعلی Jira",
    jiraUrl: "آدرس Jira",
    jiraUrlPlaceholder: "https://jira.company.com",
    connect: "اتصال",
    skipForNow: "فعلاً رد کن",
    chooseJiraTab: "تب‌های Jira",
    chooseJiraTabHint: "چند تب Jira باز است. درخواست‌ها از تب انتخاب‌شده ارسال می‌شوند و می‌توانید از اینجا بین آن‌ها جابه‌جا شوید.",
    useThisTab: "استفاده از این تب",
    tabInUse: "در حال استفاده",
    noJiraTabs: "برای این سایت هیچ تب Jira بازی پیدا نشد.",
    connectedSite: "سایت متصل",
    differentJiraSite: "یک سایت Jira دیگر شناسایی شد",
    differentJiraSiteDescription: "اکستنشن از یک Jira دیگر باز شده است. اگر می‌خواهید Workspace را عوض کنید، آن را متصل کنید.",
    multipleTabsToast: "چند تب Jira شناسایی شد",
    multipleTabsDescription: "از آخرین تب انتخاب‌شده Jira استفاده می‌شود. از پنل اتصال می‌توانید تب را عوض کنید.",
    contextDetected: "کانتکست Jira شناسایی شد",
    contextDetectedDescription: "پروژه و بورد از تب Jira فعلی شما تشخیص داده شد.",
    activeSprintDetected: "اسپرینت فعال انتخاب شد",
    connectionReady: "Jira متصل شد",
    connectionFailed: "اتصال به Jira انجام نشد",
    validationPassed: "اعتبارسنجی موفق بود",
    validationFailed: "قبل از ساخت، خطاهای اعتبارسنجی را برطرف کنید",
    createSucceeded: "تسک‌ها با موفقیت ساخته شدند",
    quickCreateSucceeded: "تسک با موفقیت ساخته شد",
    updateSucceeded: "تسک‌های Jira به‌روزرسانی شدند",
    deleteSucceeded: "تسک‌های انتخاب‌شده حذف شدند",
    importSucceeded: "دسته تسک‌ها وارد شد",
    importFailed: "خواندن این دسته Jira ممکن نبود",
    quick: "ساخت سریع",
    bulk: "ورود گروهی",
    review: "مرور و ساخت",
    manage: "مدیریت Jira",
    quickTitle: "ساخت سریع یک تسک",
    quickHint: "برای تسکی که همین الان لازم داری، بدون رفتن سراغ JSON.",
    bulkTitle: "ورود گروهی تسک‌ها",
    bulkHint: "JSON را Paste کن، فایل بده یا نمونه امن را برای AI دانلود کن.",
    reviewTitle: "مرور قبل از Jira",
    reviewHint: "جای قرارگیری و جزئیات را بررسی کن؛ JSON فقط وقتی لازم است دیده می‌شود.",
    manageTitle: "مدیریت تسک‌های ساخته‌شده",
    manageHint: "بعد از ساخت، اسپرینت، اولویت، مسئول، استیمیت یا حذف گروهی را مستقیم روی Jira مدیریت کن.",
    contextMismatchTitle: "کانتکست Jira با Workspace فعلی یکی نیست",
    contextMismatchDescription: "تب Jira فعلی مربوط به پروژه دیگری است. مشخص کن کدام کانتکست مبنای این Workspace باشد.",
    useCurrentJiraContext: "استفاده از کانتکست Jira فعلی",
    keepWorkspace: "نگه داشتن Workspace فعلی",
    chooseTab: "انتخاب تب Jira",
    skippedOnboardingTitle: "هنوز Jira متصل نشده",
    skippedOnboardingDescription: "همان تب Jira که الان استفاده می‌کنی را متصل کن؛ پیش‌نویس فعلی دست‌نخورده می‌ماند.",
    largeBoardHint: "بورد بزرگ شناسایی شد. نمای لیستی برای مرور سریع و ویرایش گروهی مناسب‌تر است.",
    listView: "لیست",
    boardViewLive: "بورد",
    filtersLabel: "فیلترها",
    myIssues: "تسک‌های من",
    allAssignees: "همه مسئول‌ها",
    allPriorities: "همه اولویت‌ها",
    allStatuses: "همه وضعیت‌ها",
    allSprints: "همه اسپرینت‌ها",
    allLabels: "همه برچسب‌ها",
    allEstimates: "همه استیمیت‌ها",
    estimated: "دارای استیمیت",
    unestimated: "بدون استیمیت",
    activeFilters: "فیلتر فعال",
    clearFilters: "پاک کردن فیلترها",
    selectVisible: "انتخاب موارد این صفحه",
    selectMatching: "انتخاب همه نتایج",
    selectedMatching: "همه نتایج فیلترشده انتخاب شدند",
    page: "صفحه",
    of: "از",
    rowsPerPage: "تعداد ردیف",
    estimate: "استیمیت",
    storyPoints: "Story Point",
    originalEstimate: "استیمیت اولیه",
    remainingEstimate: "استیمیت باقی‌مانده",
    estimatePlaceholder: "مثلاً 3h، 2d یا 30m",
    estimateHelp: "فرمت زمان Jira: مثل 30m، 3h، 2d یا ترکیبی مثل 1d 4h.",
    defaultEstimate: "استیمیت پیش‌فرض",
    inheritedEstimate: "اگر خالی باشد از مقدار گروهی استفاده می‌کند",
    estimateUnavailable: "Time Tracking برای این اتصال Jira در دسترس نیست.",
    estimateApplyFailed: "بعضی استیمیت‌ها اعمال نشدند",
    editEstimate: "تغییر استیمیت",
    status: "وضعیت",
    open: "باز کردن",
    bulkActions: "عملیات گروهی",
    createdBatch: "دسته ساخته‌شده",
    wholeBoard: "کل بورد",
    refreshBoard: "تازه‌سازی بورد",
    bulkEdit: "ویرایش گروهی",
    bulkEditPreview: "مرور تغییرات",
    bulkEditPreviewHint: "قبل از نوشتن روی Jira، مقدار فعلی و مقدار جدید را بررسی کن.",
    beforeValue: "قبل",
    afterValue: "بعد",
    confirmBulkEdit: "اعمال در Jira",
    backToEdit: "بازگشت به ویرایش",
    preparingPreview: "در حال آماده‌سازی پیش‌نمایش تغییرات…",
    dynamicFields: "فیلدهای بیشتر Jira",
    dynamicFieldsHint: "این فیلدها از اطلاعات ویرایش Jira برای تمام تسک‌های انتخاب‌شده خوانده می‌شوند.",
    addJiraField: "افزودن فیلد Jira",
    noDynamicFields: "Jira برای این انتخاب فیلد قابل ویرایش بیشتری برنگرداند.",
    fieldAvailability: "در {count} از {total} تسک انتخاب‌شده در دسترس است",
    setValue: "ثبت مقدار",
    clearValue: "پاک کردن مقدار",
    removeField: "حذف فیلد",
    fieldRequired: "اجباری",
    editMetadataFailed: "QueueMint نتوانست امکان ویرایش این انتخاب را در Jira تایید کند.",
    bulkFieldGuardHint: "فیلدهایی که Jira روی همه تسک‌های انتخاب‌شده اجازه ویرایششان را نمی‌دهد قبل از Review غیرفعال می‌شوند.",
    fieldNotEditable: "فیلد {field} روی {count} تسک انتخاب‌شده قابل ویرایش نیست.",
    timeTrackingScreenHint: "Time Tracking در صفحه Edit همه تسک‌های انتخاب‌شده در دسترس نیست.",
    mixedValues: "مقادیر متفاوت",
    history: "تاریخچه",
    changeHistory: "تاریخچه تغییرات گروهی",
    historyHint: "تغییرات گروهی اخیر این نشست نگه داشته می‌شوند تا بتوانی مقدارهای قبلی را برگردانی.",
    noHistory: "هنوز تغییر گروهی ثبت نشده است.",
    undo: "بازگردانی",
    undoing: "در حال بازگردانی…",
    undoComplete: "مقادیر قبلی Jira برگردانده شدند.",
    undoPartial: "بعضی مقدارهای Jira قابل بازگردانی نبودند.",
    changes: "تغییر",
    issuesAffected: "تسک تحت تاثیر",
    assignToMe: "اختصاص به من",
    applyChanges: "اعمال تغییرات",
    noChange: "بدون تغییر",
    selectedIssues: "تسک انتخاب‌شده",
    deleteSelected: "حذف انتخاب‌شده‌ها",
    confirmDeleteTitle: "تسک‌های انتخاب‌شده از Jira حذف شوند؟",
    confirmDeleteDescription: "این عملیات قابل بازگشت نیست. برای تأیید حذف، DELETE را تایپ کن.",
    typeDelete: "DELETE را تایپ کن",
    deleteNow: "حذف دائمی",
    boardEmpty: "در این نمای بورد تسکی پیدا نشد.",
    boardLoading: "در حال خواندن بورد Jira…",
    dragHint: "کارت‌ها را بین Sprint و Backlog بکش؛ برای دسترسی با کیبورد هم عملیات گروهی در دسترس است.",
    draftCleared: "تسک‌ها ساخته شدند و پیش‌نویس دسته پاک شد.",
    createdReviewPlacement: "تسک‌ها ساخته شدند؛ چون Jira همه موارد را طبق برنامه در Sprint قرار نداد، وضعیت Sprint/Backlog را در بورد زیر بررسی کن.",
    createdReviewEstimate: "تسک‌ها ساخته شدند، اما بعضی استیمیت‌ها نیاز به بررسی دارند. از ویرایش گروهی پایین برای اصلاح استفاده کن.",
    postCreateHelp: "این تسک‌ها همین حالا در Jira وجود دارند و تغییرات این بخش مستقیماً روی Jira اعمال می‌شود.",
    editPriority: "تغییر اولویت",
    editAssignee: "تغییر مسئول",
    editPlacement: "تغییر محل",
    editIssueType: "تغییر نوع تسک",
    editEpicLink: "تغییر Epic Link",
    removeEpicLink: "حذف Epic Link",
    unassign: "بدون مسئول",
    permissionsDenied: "دسترسی Jira شما اجازه این عملیات را نمی‌دهد.",
    updateComplete: "ویرایش گروهی انجام شد.",
    updatePartial: "بعضی تسک‌های Jira به‌روزرسانی نشدند.",
    deleteComplete: "تسک‌های انتخاب‌شده از Jira حذف شدند.",
    project: "پروژه",
    board: "برد",
} as const
